name: 'Test Pipeline'

on:
  push:
    branches:
      - 'main'

jobs:
  credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
  default_param:
    needs: credentials
    runs-on: ubuntu-latest
    steps:
      - name: Fetch parameters from AWS SSM parameter store
        uses: oneyedev/aws-fetch-ssm-parameter-store@main
      - name: Assert Environment Variables
        if: ${{ env.SAMPLE_ROOT_KEY != 'THIS IS A SAMPLE ROOT VALUE' }}
        run: |
          echo "SAMPLE_ROOT_KEY: $SAMPLE_ROOT_KEY"
          echo "::error ::Assert Fails"
          exit 1
  path_param:
    needs: credentials
    runs-on: ubuntu-latest
    steps:
      - name: Fetch parameters from AWS SSM parameter store
        uses: oneyedev/aws-fetch-ssm-parameter-store@main
        with:
          path: /sample
      - name: Assert Environment Variables
        if: ${{ env.sample/SAMPLE_KEY != 'this is a sample key' }}
        run: |
          echo "sample/SAMPLE_KEY: $sample/SAMPLE_KEY"
          echo "::error ::Assert Fails"
          exit 1
  replace_param:
    needs: credentials
    runs-on: ubuntu-latest
    steps:
      - name: Fetch parameters from AWS SSM parameter store
        uses: oneyedev/aws-fetch-ssm-parameter-store@main
        with:
          path: /sample
          replacePathWithEmpty: true
      - name: Assert Environment Variables
        if: ${{ env.SAMPLE_KEY != 'this is a sample key' }}
        run: |
          echo "SAMPLE_KEY: $SAMPLE_KEY"
          echo "::error ::Assert Fails"
          exit 1
  recursive_param:
    needs: credentials
    runs-on: ubuntu-latest
    steps:
      - name: Fetch parameters from AWS SSM parameter store
        uses: oneyedev/aws-fetch-ssm-parameter-store@main
        with:
          path: /sample
          recursive: true
      - name: Assert Environment Variables
        if: ${{ env./sample/SAMPLE_KEY != 'this is a sample key' || env./sample/nested/NESTED_KEY != 'this is a nested value' }}
        run: |
          echo "/sample/SAMPLE_KEY: $/sample/SAMPLE_KEY"
          echo "/sample/nested/NESTED_KEY: $/sample/nested/NESTED_KEY"
          echo "::error ::Assert Fails"
          exit 1
